apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rendered-production
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/skiyl9x/gitops.git
  ref:
    branch: production
