apiVersion: v1
kind: Namespace
metadata:
  name: apps-backend-prod
---
apiVersion: v1
kind: LimitRange
metadata:
  name: apps-backend-prod
  namespace: apps-backend-prod
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    type: Container
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-backend-prod
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/prod/backend/
  prune: true
  sourceRef:
    kind: GitRepository
    name: rendered-prod
  targetNamespace: apps-backend-prod
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: shared-vars-prod
