apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kiali-operator
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
      version: 1.89.x
  install:
    createNamespace: true
  interval: 1h
  targetNamespace: kiali-operator
  values:
    kiali_vars:
      external_services:
        istio:
          gateway_api_classes:
          - class_name: traefik
            name: Traefik
