apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali
  namespace: istio-system
spec:
  hostnames:
  - kiali.${cluster_domain}
  parentRefs:
  - kind: Gateway
    name: traefik-gateway
    namespace: traefik-system
    sectionName: websecure
  rules:
  - backendRefs:
    - name: kiali
      port: 20001
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: anonymous
  deployment:
    instance_name: kiali
    namespace: istio-system
    view_only_mode: false
  external_services:
    grafana:
      enabled: true
      url: http://kube-prometheus-stack-grafana.monitoring-system.svc.cluster.local:3000
    istio:
      gateway_api_classes:
      - class_name: istio
        name: Istio
      - class_name: traefik
        name: Traefik
    prometheus:
      url: http://kube-prometheus-stack-prometheus.monitoring-system.svc:9090
