apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-01-skiyl9x-pp-ua-tls
  namespace: traefik-system
spec:
  dnsNames:
  - dev-01.skiyl9x.pp.ua
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns-issuer
  secretName: dev-01-skiyl9x-pp-ua-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-01-skiyl9x-pp-ua-wildcard-tls
  namespace: traefik-system
spec:
  dnsNames:
  - '*.dev-01.skiyl9x.pp.ua'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns-issuer
  secretName: dev-01-skiyl9x-pp-ua-wildcard-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-skiyl9x-pp-ua-wildcard-tls
  namespace: traefik-system
spec:
  dnsNames:
  - '*.dev.skiyl9x.pp.ua'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns-issuer
  secretName: dev-skiyl9x-pp-ua-wildcard-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-01-skiyl9x-pp-ua-tls
  namespace: traefik-system
spec:
  dnsNames:
  - prod-01.skiyl9x.pp.ua
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns-issuer
  secretName: prod-01-skiyl9x-pp-ua-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-01-skiyl9x-pp-ua-wildcard-tls
  namespace: traefik-system
spec:
  dnsNames:
  - '*.prod-01.skiyl9x.pp.ua'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns-issuer
  secretName: prod-01-skiyl9x-pp-ua-wildcard-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-skiyl9x-pp-ua-wildcard-tls
  namespace: traefik-system
spec:
  dnsNames:
  - '*.prod.skiyl9x.pp.ua'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns-issuer
  secretName: prod-skiyl9x-pp-ua-wildcard-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stage-01-skiyl9x-pp-ua-tls
  namespace: traefik-system
spec:
  dnsNames:
  - stage-01.skiyl9x.pp.ua
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns-issuer
  secretName: stage-01-skiyl9x-pp-ua-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stage-01-skiyl9x-pp-ua-wildcard-tls
  namespace: traefik-system
spec:
  dnsNames:
  - '*.stage-01.skiyl9x.pp.ua'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns-issuer
  secretName: stage-01-skiyl9x-pp-ua-wildcard-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stage-skiyl9x-pp-ua-wildcard-tls
  namespace: traefik-system
spec:
  dnsNames:
  - '*.stage.skiyl9x.pp.ua'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns-issuer
  secretName: stage-skiyl9x-pp-ua-wildcard-tls
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 39.0.0
  install:
    createNamespace: true
  interval: 1m
  releaseName: traefik
  storageNamespace: traefik-system
  targetNamespace: traefik-system
  values:
    gateway:
      enabled: true
      listeners:
        web:
          namespacePolicy:
            from: All
          port: 80
        websecure:
          certificateRefs:
          - group: ""
            kind: Secret
            name: nginx-dev-01-skiyl9x-pp-ua-tls
            namespace: traefik-system
          - group: ""
            kind: Secret
            name: dev-01-skiyl9x-pp-ua-tls
            namespace: traefik-system
          mode: Terminate
          namespacePolicy:
            from: All
          port: 443
          protocol: HTTPS
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints:
        - websecure
        matchRule: Host(`traefik-dashboard.${cluster_domain}`)
    logs:
      access:
        enabled: true
        fields:
          headers:
            defaultMode: keep
        format: json
    ports:
      traefik:
        expose:
          default: true
      web:
        exposedPort: 80
        port: 80
      websecure:
        exposedPort: 443
        http:
          tls:
            enabled: true
        port: 443
    providers:
      kubernetesGateway:
        enabled: true
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik-system
spec:
  certificates:
  - secretName: dev-01-skiyl9x-pp-ua-tls
  - secretName: dev-01-skiyl9x-pp-ua-wildcard-tls
  - secretName: dev-skiyl9x-pp-ua-wildcard-tls
  - secretName: stage-01-skiyl9x-pp-ua-tls
  - secretName: stage-01-skiyl9x-pp-ua-wildcard-tls
  - secretName: stage-skiyl9x-pp-ua-wildcard-tls
  - secretName: prod-01-skiyl9x-pp-ua-tls
  - secretName: prod-01-skiyl9x-pp-ua-wildcard-tls
  - secretName: prod-skiyl9x-pp-ua-wildcard-tls
