apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-oleks-01-skiyl9x-pp-ua-wildcard-tls
  namespace: traefik-system
spec:
  secretName: dev-oleks-01-skiyl9x-pp-ua-wildcard-tls
  issuerRef:
    name: letsencrypt-dns-issuer
    kind: ClusterIssuer
  dnsNames:
    - "dev-oleks-01.skiyl9x.pp.ua"
    - "*.dev-oleks-01.skiyl9x.pp.ua"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infra-dev-skiyl9x-pp-ua-wildcard-tls
  namespace: traefik-system
spec:
  secretName: infra-dev-skiyl9x-pp-ua-wildcard-tls
  issuerRef:
    name: letsencrypt-dns-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.infra.dev.skiyl9x.pp.ua"
