apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stage-skiyl9x-pp-ua-wildcard-tls
  namespace: traefik-system
spec:
  secretName: stage-skiyl9x-pp-ua-wildcard-tls
  issuerRef:
    name: letsencrypt-dns-issuer
    kind: ClusterIssuer
  dnsNames:
    - "stage.skiyl9x.pp.ua"
    - "*.stage.skiyl9x.pp.ua"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infra-stage-skiyl9x-pp-ua-wildcard-tls
  namespace: traefik-system
spec:
  secretName: infra-stage-skiyl9x-pp-ua-wildcatd-tls
  issuerRef:
    name: letsencrypt-dns-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.infra.stage.skiyl9x.pp.ua"
