apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  releaseName: traefik
  targetNamespace: traefik-system
  storageNamespace: traefik-system
  install:
    createNamespace: true
  interval: 1m
  chart:
    spec:
      chart: traefik
      version: "39.0.0" # Adjust based on current latest version
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    # Optional: Enable the Traefik Dashboard
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik-dashboard.${cluster_domain}`)
        entryPoints:
          - web
    # Enable the modern Gateway API provider
    providers:
      kubernetesGateway:
        enabled: true
    gateway:
      listeners:
        web:
          namespacePolicy:
            from: All
      annotations:
        traefik.io/gateway.tls.certresolver: cloudflare
    ports:
      web:
        port: 8000 # Matches --entryPoints.web.address
        exposedPort: 80 # What you'll use in your browser (http://<IP>)
      websecure:
        port: 8443 # Matches --entryPoints.websecure.address
        exposedPort: 443 # What you'll use in your browser (https://<IP>)
        tls:
          mode: Terminate
      traefik:
        expose:
          default: true
    logs:
      access:
        enabled: true
        # Optional: customize format (common or json)
        format: json
        # Optional: track specific headers
        fields:
          headers:
            defaultMode: keep
    volumes:
      - name: cloudflare-api-token
        mountPath: /etc/secrets
        type: secret
    env:
      - name: CF_DNS_API_TOKEN_FILE
        value: "/etc/secrets/api-token"

    certificatesResolvers:
      cloudflare:
        acme:
          email: skiyl9x@gmail.com
          storage: /data/acme.json
          dnsChallenge:
            provider: cloudflare
