apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  releaseName: traefik
  targetNamespace: traefik-system
  storageNamespace: traefik-system
  install:
    createNamespace: true
  interval: 1m
  chart:
    spec:
      chart: traefik
      version: "39.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    gateway:
      enabled: true
      listeners:
        # Configure the web listener to allow traffic from all namespaces
        web:
          port: 8000
          namespacePolicy:
            from: All
        # Configure the websecure listener to use TLS with the specified certificate and allow traffic from all namespaces
        websecure:
          port: 8443
          protocol: HTTPS
          mode: Terminate
          certificateRefs:
            - name: app-certs
              kind: Secret
          namespacePolicy:
            from: All
    ingressRoute:
      # Enable the dashboard IngressRoute with a match rule for the specified domain
      dashboard:
        enabled: true
        matchRule: Host(`traefik-dashboard.${cluster_domain}`)
        entryPoints:
          - websecure
    logs:
      # Enable access logs in JSON format and keep all header fields
      access:
        enabled: true
        format: json
        fields:
          headers:
            defaultMode: keep
    ports:
      # Expose the dashboard on port 8080
      traefik:
        expose:
          default: true
      # Expose the web entrypoint on port 80
      web:
        port: 8000
        exposedPort: 80
      # Expose the websecure entrypoint on port 443
      websecure:
        port: 8443
        exposedPort: 443
        http:
          tls:
            enabled: true
    # Enable the Gateway API provider
    providers:
      kubernetesGateway:
        enabled: true

