apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik-system
spec:
  certificates:
    - secretName: dev-01-skiyl9x-pp-ua-wildcard-tls
    - secretName: infra-dev-skiyl9x-pp-ua-wildcard-tls
    - secretName: stage-skiyl9x-pp-ua-wildcard-tls
    - secretName: infra-stage-skiyl9x-pp-ua-wildcard-tls
    - secretName: prod-skiyl9x-pp-ua-wildcard-tls
    - secretName: infra-prod-skiyl9x-pp-ua-wildcard-tls
